# site settings
title: Alexander Rotella's Portfolio
subtitle: 
email: arotella1221@gmail.com
description: A summary of my experience as an aspiring Software Engineer.
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://alex-rotella.github.io # the base hostname & protocol for your site
author:


# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/Alex-Rotella
  LinkedIn: https://www.linkedin.com/in/alexander-rotella-373351136/


# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
